CREATE TABLE color (id INT NOT NULL AUTO_INCREMENT, Name TEXT, Rgb TEXT, PRIMARY KEY (id));
insert into color (Name, Rgb) values('Aiguamarina','#7FFFD4');
insert into color (Name, Rgb) values('Albercoc','#FBCEB1');
insert into color (Name, Rgb) values('Amarant','#E52B50');
insert into color (Name, Rgb) values('Ambre','#FFBF00');
insert into color (Name, Rgb) values('Ametista','#9966CC');
insert into color (Name, Rgb) values('Atzur','#007FFF');
insert into color (Name, Rgb) values('Beix','#F5F5DC');
insert into color (Name, Rgb) values('Bistre','#3D2B1F');
insert into color (Name, Rgb) values('Blanc','#FFFFFF');
insert into color (Name, Rgb) values('Blat','#F5DEB3');
insert into color (Name, Rgb) values('Blau','#0000FF');
insert into color (Name, Rgb) values('Blau cel','#77B5FE');
insert into color (Name, Rgb) values('Blau de cobalt','#0047AB');
insert into color (Name, Rgb) values('Blau de França','#318CE7');
insert into color (Name, Rgb) values('Blau de Prússia','#003153');
insert into color (Name, Rgb) values('Blau fosc','#00008B');
insert into color (Name, Rgb) values('Blau marí','#000080');
insert into color (Name, Rgb) values('Blau reial','#002366');
insert into color (Name, Rgb) values('Blauet','#003399');
insert into color (Name, Rgb) values('Bronze','#CD7F32');
insert into color (Name, Rgb) values('Camussa','#F0DC82');
insert into color (Name, Rgb) values('Canyella','#D2B48C');
insert into color (Name, Rgb) values('Caqui','#C3B091');
insert into color (Name, Rgb) values('Cardenal','#C41E3A');
insert into color (Name, Rgb) values('Carmesí','#DC143C');
insert into color (Name, Rgb) values('Carmí','#960018');
insert into color (Name, Rgb) values('Carnació','#FEC3AC');
insert into color (Name, Rgb) values('Castany rogenc','#CC8899');
insert into color (Name, Rgb) values('Celadont','#2F847C');
insert into color (Name, Rgb) values('Ceruli','#007BA7');
insert into color (Name, Rgb) values('Chartreuse','#7FFF00');
insert into color (Name, Rgb) values('Cian','#00FFFF');
insert into color (Name, Rgb) values('Cirera','#DE3163');
insert into color (Name, Rgb) values('Corall','#FF7F50');
insert into color (Name, Rgb) values('Coure','#B87333');
insert into color (Name, Rgb) values('Crema','#FFFDD0');
insert into color (Name, Rgb) values('Escarlata','#FF2400');
insert into color (Name, Rgb) values('Fúcsia','#E13571');
insert into color (Name, Rgb) values('Granat','#800000');
insert into color (Name, Rgb) values('Gris','#AAAAAA');
insert into color (Name, Rgb) values('Gris fosc','#808080');
insert into color (Name, Rgb) values('Groc','#FFFF00');
insert into color (Name, Rgb) values('Heliotropi','#DF73FF');
insert into color (Name, Rgb) values('Indi','#4B0082');
insert into color (Name, Rgb) values('Jade','#00A86B');
insert into color (Name, Rgb) values('Lavanda','#E6E6FA');
insert into color (Name, Rgb) values('Lila','#660099');
insert into color (Name, Rgb) values('Llima','#CCFF00');
insert into color (Name, Rgb) values('Magenta','#FF00FF');
insert into color (Name, Rgb) values('Malva','#E0B0FF');
insert into color (Name, Rgb) values('Marró','#964B00');
insert into color (Name, Rgb) values('Morat','#C54B8C');
insert into color (Name, Rgb) values('Negre','#000000');
insert into color (Name, Rgb) values('Ocre','#CC7722');
insert into color (Name, Rgb) values('Or','#FFD700');
insert into color (Name, Rgb) values('Orquídia','#DA70D6');
insert into color (Name, Rgb) values('Panotxa','#CC5500');
insert into color (Name, Rgb) values('Plata','#C0C0C0');
insert into color (Name, Rgb) values('Porpra','#800080');
insert into color (Name, Rgb) values('Préssec','#FFE5B4');
insert into color (Name, Rgb) values('Pruna','#660066');
insert into color (Name, Rgb) values('Rosa','#FFC0CB');
insert into color (Name, Rgb) values('Salmó','#FF8C69');
insert into color (Name, Rgb) values('Sèpia','#704214');
insert into color (Name, Rgb) values('Taronja','#FF7F00');
insert into color (Name, Rgb) values('Turquesa','#30D5C8');
insert into color (Name, Rgb) values('Verd','#00FF00');
insert into color (Name, Rgb) values('Verd maragda','#50C878');
insert into color (Name, Rgb) values('Verd oliva','#808000');
insert into color (Name, Rgb) values('Verd veronès','#40826D');
insert into color (Name, Rgb) values('Vermell','#FF0000');
insert into color (Name, Rgb) values('Vermell fosc','#8B0000');
insert into color (Name, Rgb) values('Vermelló','#E34234');
insert into color (Name, Rgb) values('Vinca','#CCCCFF');
insert into color (Name, Rgb) values('Violat','#8B00FF');
insert into color (Name, Rgb) values('Vori','#FFFFF0');
insert into color (Name, Rgb) values('Xarxet','#008080');

